# Dockerfile localizado em sulla/backend

FROM node:20

# Defina o diretório de trabalho
WORKDIR /app

# Instale Chromium e suas dependências
RUN apt-get update && apt-get install -y chromium

# Copie todos os arquivos da pasta backend para o container
COPY . .

# Instale as dependências
RUN npm install

# Exponha a porta 3001
EXPOSE 3001

# Comando para iniciar a aplicação
CMD ["npm", "start"]
