FROM node:20

# Defina o diretório de trabalho
WORKDIR /app

# Instale o Git
RUN apt-get update && apt-get install -y git

# Clone o repositório com sparse-checkout para a pasta frontend
RUN git clone --no-checkout https://github.com/thiagosmpa/sulla.git /app/sulla
WORKDIR /app/sulla
RUN git sparse-checkout init --cone
RUN git sparse-checkout set frontend
RUN git checkout

# Navegue para o diretório desejado
WORKDIR /app/sulla/frontend

# Copie e instale as dependências
COPY package*.json ./
RUN npm install

# Execute o build da aplicação
RUN npm run build

# Exponha a porta 3000
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
