FROM node:20

# Defina o diretório de trabalho
WORKDIR /app

# Instale o Git
RUN apt-get update && apt-get install -y git

# Inicialize um novo repositório Git
RUN git init

# Adicione o repositório remoto
RUN git remote add -f origin https://github.com/thiagosmpa/sulla.git

# Habilite o sparse-checkout e defina a pasta desejada
RUN git config core.sparseCheckout true
RUN echo "frontend" >> .git/info/sparse-checkout

# Faça o checkout do repositório
RUN git pull origin main

# Navegue para o diretório desejado
WORKDIR /app/sulla/frontend

# Copie e instale as dependências
RUN npm install

# Execute o build da aplicação
RUN npm run build

# Exponha a porta 3000
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
