version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://thiagomachado:99747-Thi@db:5432/thiagomachado
      - WHATSAPP_SERVER_URL=http://whatsapp:3002
      - JWT_SECRET=secret
      - WHATSAPP_AUTH_PATH=./whatsapp/auth
      - AGENT_API_URL=http://agent_api:18070/message
      - W_PORT=3002
      - B_PORT=3001
      - F_PORT=3000
      - BACKEND_URL=http://backend:3001
    depends_on:
      - backend
      - whatsapp

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://thiagomachado:99747-Thi@db:5432/thiagomachado
      - WHATSAPP_SERVER_URL=http://whatsapp:3002
      - JWT_SECRET=secret
      - WHATSAPP_AUTH_PATH=./whatsapp/auth
      - AGENT_API_URL=http://agent_api:18070/message
      - W_PORT=3002
      - B_PORT=3001
      - F_PORT=3000
    depends_on:
      - db
      - whatsapp

  whatsapp:
    build:
      context: ./whatsapp
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://thiagomachado:99747-Thi@db:5432/thiagomachado
      - WHATSAPP_SERVER_URL=http://whatsapp:3002
      - JWT_SECRET=secret
      - WHATSAPP_AUTH_PATH=./whatsapp/auth
      - AGENT_API_URL=http://agent_api:18070/message
      - W_PORT=3002
      - B_PORT=3001
      - F_PORT=3000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: thiagomachado
      POSTGRES_PASSWORD: 99747-Thi
      POSTGRES_DB: thiagomachado
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
