FROM node:20

# Defina o diretório de trabalho
WORKDIR /app

# Instale o Git e Chromium
RUN apt-get update && apt-get install -y git chromium

# Clone o repositório com sparse-checkout para a pasta backend
RUN git clone --no-checkout https://github.com/thiagosmpa/sulla.git /app/sulla
WORKDIR /app/sulla
RUN git sparse-checkout init --cone
RUN git sparse-checkout set backend
RUN git checkout

# Navegue para o diretório desejado
WORKDIR /app/sulla/backend

# Copie e instale as dependências
RUN npm install

# Defina a variável de ambiente DATABASE_URL
ENV DATABASE_URL=postgresql://thiagomachado:99747-Thi@db:5432/thiagomachado

# Execute as migrações
RUN npm run migrate

# Execute o build da aplicação
RUN npm run build

# Exponha a porta 3001
EXPOSE 3001

# Comando para iniciar a aplicação
CMD ["npm", "start"]
