# Use a imagem base do Python 3.10
FROM python:3.10

# Defina o diretório de trabalho
WORKDIR /app

# Instale o Git
RUN apt-get update && apt-get install -y git

# Clone o repositório com sparse-checkout para a pasta chatgpt
RUN git clone --no-checkout https://github.com/thiagosmpa/sulla.git /app/sulla
WORKDIR /app/sulla
RUN git sparse-checkout init --cone
RUN git sparse-checkout set chatgpt
RUN git checkout

# Navegue para o diretório desejado
WORKDIR /app/sulla/chatgpt

# Instale as dependências listadas em requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Exponha a porta 3004
EXPOSE 3004

# Comando para iniciar a aplicação
CMD ["python", "app.py"]
