# Use a imagem base do Node.js 20
FROM node:20

# Defina o diretório de trabalho
WORKDIR /app

# Instale o Git
RUN apt-get update && apt-get install -y git

# Copie todos os arquivos da pasta frontend para o container
COPY . .

# Instale as dependências
RUN npm install

# Execute o build da aplicação
RUN npm run build

# Exponha a porta 3000
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
