FROM node:20

# Defina o diretório de trabalho
WORKDIR /usr/src/app

# Instale o Git
RUN apt-get update && apt-get install -y git

# Clone o repositório com sparse-checkout para a pasta whatsapp
RUN git clone --no-checkout https://github.com/thiagosmpa/sulla.git /usr/src/app/sulla
WORKDIR /usr/src/app/sulla
RUN git sparse-checkout init --cone
RUN git sparse-checkout set whatsapp
RUN git checkout

# Navegue para o diretório desejado
WORKDIR /usr/src/app/sulla/whatsapp

# Copie e instale as dependências
RUN npm install

# Exponha a porta 3002
EXPOSE 3002

# Comando para iniciar a aplicação
CMD ["npm", "start"]
