# Use a imagem base do Node.js 20
FROM node:20

# Defina o diretório de trabalho
WORKDIR /usr/src/app

# Instale o Git
RUN apt-get update && apt-get install -y git

# Copie todos os arquivos da pasta whatsapp para o container
COPY . .

# Instale as dependências
RUN npm install

# Exponha a porta 3002
EXPOSE 3002

# Comando para iniciar a aplicação
CMD ["npm", "start"]
